client/build.gradle, client/src/main/java/com/jraska/github/client/settings/PurchaseReportModel.kt, client/src/main/java/com/jraska/github/client/settings/SettingsActivity.kt, client/src/main/java/com/jraska/github/client/ui/BaseActivity.kt, client/src/main/java/com/jraska/github/client/ui/RepoDetailActivity.kt, client/src/main/java/com/jraska/github/client/ui/RepoDetailHeaderModel.kt, client/src/main/java/com/jraska/github/client/ui/RepoHeaderModel.kt, client/src/main/java/com/jraska/github/client/ui/ReposSectionModel.kt, client/src/main/java/com/jraska/github/client/ui/UserDetailActivity.kt, client/src/main/java/com/jraska/github/client/ui/UserHeaderModel.kt, client/src/main/java/com/jraska/github/client/ui/UserModel.kt, client/src/main/java/com/jraska/github/client/ui/UsersActivity.kt, client/src/main/java/com/jraska/github/client/ui/View.kt
=> Remove butterknife

client/build.gradle, client/proguard-rules.pro
- Add proguard-rules and minify the app on release
=> Enable Proguard

app/build.gradle, build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/com/jraska/github/client/tasks/AssertLayersOrderTask.kt, buildSrc/src/main/java/com/jraska/github/client/tasks/AssertNoInLayerDependencies.kt, buildSrc/src/main/java/com/jraska/github/client/tasks/GenerateModulesGraphTask.kt, buildSrc/src/main/java/com/jraska/module/graph/Api.kt, buildSrc/src/main/java/com/jraska/module/graph/GraphRulesExtension.kt, buildSrc/src/main/java/com/jraska/module/graph/ModuleGraphAssertionsPlugin.kt
- plugin done
- Kotlin updated
=> Add Gradle plugin to aggregate all graph tasks

app/src/androidTest/java/com/jraska/github/client/FirebaseEventConverterTest.kt, app/src/main/java/com/jraska/github/client/FirebaseConfigProxy.kt, app/src/main/java/com/jraska/github/client/FirebaseModule.kt, core-android/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt, core-android/src/main/java/com/jraska/github/client/core/android/UriHandlerViewModel.kt, core-android/src/main/java/com/jraska/github/client/core/android/logging/AnalyticsLoggingTree.kt, core-testing/src/main/java/com/jraska/github/client/FakeConfig.kt, core/src/main/java/com/jraska/github/client/Config.kt, core/src/main/java/com/jraska/github/client/Owner.kt, core/src/main/java/com/jraska/github/client/analytics/AnalyticsEvent.kt, feature/about/src/main/java/com/jraska/github/client/about/AboutViewModel.kt, feature/push/src/main/java/com/jraska/github/client/push/ConfigAsPropertyCommand.kt, feature/push/src/main/java/com/jraska/github/client/push/PushAnalytics.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsViewModel.kt, feature/shortcuts/src/main/java/com/jraska/github/client/shortcuts/ShortcutHandlerModel.kt, feature/users/src/main/java/com/jraska/github/client/users/UserDetailViewModel.kt, feature/users/src/main/java/com/jraska/github/client/users/UsersViewModel.kt, feature/users/src/main/java/com/jraska/github/client/users/model/RepoDetailViewModel.kt
- Ownership of config and analytics is not clear after some time passes.
- We need to know if these keys are still used or not - they are usually used in external system and there is no visibility on this in code.
- Config and analytics names can be scattered around the code.
- Ownership configuration is moved into code and is enforced by config and analytics API
- Enforcing same format of introducing keys - no discussion of constant/not constant.
- Configs and analytics keys are easily searchable - see screenshot
Analytics Keys with owners         |  Config Keys with owners
:----:|:----:
When searching for constructor, we can export our keys like into something like this:
[analytics.txt](https://github.com/jraska/github-client/files/4570601/analytics.txt)
=> Adding owner to config keys and analytics

README.md
Related to https://github.com/jraska/github-client/pull/300
=> Add push integration test to readme

plugins/src/main/java/com/jraska/gradle/buildtime/report/MixpanelReporter.kt
- Prevents build failures on reporting
- Relates to #303
=> Catch exceptions during build time reporting

feature/about/src/main/java/com/jraska/github/client/about/AboutActivity.kt, feature/about/src/main/java/com/jraska/github/client/about/VersionInfoModel.kt, feature/about/src/main/res/layout/about_item_version.xml, feature/about/src/main/res/values/strings.xml
- New Epoxy model with that info
=> Add version info to About screen

app/build.gradle, plugins/build.gradle, plugins/gradle/wrapper/gradle-wrapper.properties, plugins/src/main/java/com/jraska/github/client/release/GradleFileVersionIncrement.kt, plugins/src/main/java/com/jraska/github/client/release/ReleasePlugin.kt, plugins/src/test/kotlin/com/jraska/github/client/release/VersionIncrementTest.kt
- Kotlin updated on a way
- Some Gradle metadata added to run composite tests properly
- `incrementPatch` task added as I got tired of doing it by myself all the time
=> Update Composite builds and add Release plugin

app-partial-users/build.gradle, app/build.gradle, feature/about/build.gradle, feature/about/src/main/java/com/jraska/github/client/about/AboutActivity.kt, feature/about/src/main/java/com/jraska/github/client/about/IconModel.kt, feature/settings/build.gradle, feature/settings/src/main/java/com/jraska/github/client/settings/PurchaseReportModel.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsActivity.kt, feature/shortcuts/build.gradle, feature/users/build.gradle, feature/users/src/main/java/com/jraska/github/client/users/ui/RepoDetailActivity.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/RepoDetailHeaderModel.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/RepoHeaderModel.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/ReposSectionModel.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/UserDetailActivity.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/UserHeaderModel.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/UserModel.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/UsersActivity.kt
- Removing the plugin as we don't use Parcelable and the rest was deprecated.
- https://youtrack.jetbrains.com/issue/KT-42121
=> Remove usage of deprecated Kotlin generated view synthetics

.circleci/config.yml
- CircleCI has embedded gcloud so we don't have to install to explicitly
=> Rely on embedded gcloud on circle CI

.circleci/config.yml, plugins/src/main/java/com/jraska/gradle/buildtime/BuildReporter.kt, plugins/src/main/java/com/jraska/module/ModuleStatistics.kt, plugins/src/main/java/com/jraska/module/ModuleStatsReporter.kt, plugins/src/main/java/com/jraska/module/extract/StatisticsGradleExtractor.kt
- Adds Dependency reporting of ll direct and transitive dependencies
- Cn be used to monitor dependency hell, track dependency removal or seeing which modules are getting bloated.
- Resolves #369
=> Add dependency reporting

plugins/build.gradle
- The stuff was obsolete
- Dependabot probably doesn't see this.
=> Align versions of plugin dependencies

.github/workflows/release.yml, app/build.gradle, plugins/build.gradle, plugins/src/main/java/com/jraska/github/client/release/GitHubApi.kt, plugins/src/main/java/com/jraska/github/client/release/NotesComposer.kt, plugins/src/main/java/com/jraska/github/client/release/Release.kt, plugins/src/main/java/com/jraska/github/client/release/ReleaseMarker.kt, plugins/src/main/java/com/jraska/github/client/release/ReleaseMarksPRs.kt, plugins/src/main/java/com/jraska/github/client/release/ReleasePlugin.kt, plugins/src/main/java/com/jraska/github/client/release/data/GitHubApiFactory.kt, plugins/src/main/java/com/jraska/github/client/release/data/GitHubApiImpl.kt, plugins/src/main/java/com/jraska/github/client/release/data/GitHubInterceptor.kt, plugins/src/main/java/com/jraska/github/client/release/data/RetrofitGitHubApi.kt
- Creates milestone based on Tag
- Marks all PRs without milestone (could be improved, but not worth the effort now)
- Adds a comment about the Released stuff to the PR
- Milestone and release receive the list of PRs
- Resolves #345
=> Add marking PRs to release

plugins/src/main/java/com/jraska/github/client/release/ReleasePlugin.kt
- There was a trailing linefeed, which resulted in not finding the tag https://github.com/jraska/github-client/runs/2156206415?check_suite_focus=true
=> Trim the tag

README.md
- When one bullet list is not enough anymore...
=> Structure README by different topics demonstrated

plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseResultExtractorTest.kt
- later the tests shoul be allowed on CI - another case of no CI - useless test
=> Fix broken test for Firebase extraction

app/build.gradle, feature/about/build.gradle, feature/about/src/androidTest/java/com/jraska/github/client/about/VersionInfoModelTest.kt, feature/about/src/main/java/com/jraska/github/client/about/VersionInfoModel.kt
- example of test in module for fast local iteration
- on CI this test runs together with the app
- Related to #436 - it could still be improved as for example the activities have a dependency so they would crash
=> Instrumented test in modules

core-android-api/src/main/java/com/jraska/github/client/core/android/OnAppCreate.kt, core/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt, core/src/main/java/com/jraska/github/client/core/android/OnAppCreateAsyncExecutor.kt, feature/in-app-update/src/main/java/com/jraska/github/client/inappupdate/InAppUpdateModule.kt, feature/users/src/main/java/com/jraska/github/client/users/UsersModule.kt
- Did some profiling of the app startup and identified few bottlenecks
- The big part is system setting activity so this is hard to optimise
- One issue not addressed was logging being costly - this is now considered ok.
- Funnily enough Firebase Performance is using Protobuf Lite, which sucks and has impact on UI performance 🤦 
- _Screenshots below..._
- `OnAppCreateAsyncExecutor : OnAppCreate` was added, spinning some threads to offload startup work.
- One of the biggest contributors was Retrofit services setup - this is now done async on startup whilst the system builds the UI
- Remote config was beeing checked as part of some dependencies, this is async as well now
- Fresco init takes a long time - this got offloaded into async thread as well, though this brings a potential for crash …
=> Add OnAppCreateAsyncExecutor to parallelise some startup operations

app/build.gradle
Needed after AGP update https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.6.0
=> Update Gradle Play publisher

.github/workflows/build.yml, core-api/src/main/java/com/jraska/github/client/rx/AppSchedulers.kt
- With the remote cache this makes way more sense 
- Tasks from parallel jobs support each other
=> Run firebase separately

plugins/src/main/java/com/jraska/github/client/firebase/report/FirebaseResultExtractor.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseResultExtractorTest.kt
- Changed format with added new root node `<testsuites>`
```
<testsuite name="" tests="14" failures="0" ...
```
```
<testsuites>
<testsuite name="" tests="14" failures="0" ...
```
=> Fix Firebase Test Lab XML parsing

plugins/src/main/java/com/jraska/github/client/firebase/report/FirebaseResultExtractor.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseResultExtractorTest.kt
- Firebase changed format back after https://github.com/jraska/github-client/pull/591 - removed new root node `<testsuites>`
- Now supporting both formats
```
<testsuites>
<testsuite name="" tests="14" failures="0" ...
```
```
<testsuite name="" tests="14" failures="0" ...
```
=> Update again Firebase XML parsing

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-android-api/src/main/java/com/jraska/github/client/core/android/BaseActivity.kt, core-android-testing/build.gradle, core-testing/build.gradle, core/build.gradle, core/src/main/java/com/jraska/github/client/core/android/UriHandlerActivity.kt, dependencies.gradle, feature/about/build.gradle, feature/about/src/main/java/com/jraska/github/client/about/AboutActivity.kt, feature/chrome-custom-tabs/build.gradle, feature/network-status/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/repo/src/main/java/com/jraska/github/client/repo/ui/RepoDetailActivity.kt, feature/settings/build.gradle, feature/settings/src/main/java/com/jraska/github/client/settings/ConsoleActivity.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsActivity.kt, feature/shortcuts/build.gradle, feature/shortcuts/src/main/java/com/jraska/github/client/shortcuts/ShortcutHandlerActivity.kt, feature/ui-common-api/build.gradle, feature/users/build.gradle, feature/users/src/main/java/com/jraska/github/client/users/ui/UserDetailActivity.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/UsersActivity.kt, navigation-api/build.gradle
- Due to trasitive dependencies and different artifacts in different modules, many artifacts end up duplicated with different version
- This cause Android Studio to index them, Gradle to pull them and CI to cache them
- This PR reduced number of artifacts from 223 to 203
- Better solution is probably Platform project - this will be trialed later
=> Dependencies shaking to reduce duplicate artifacts

.github/workflows/build.yml
- Build workflows are not triggered on forked PRs - e.g. #691 
- See [GitHub docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories)
=> Add pull_request_target on build to be triggered from forked repos

plugins/src/main/java/com/jraska/gradle/buildtime/BuildTimeListener.kt
Hey, hope you're getting lots of glovo discounts 😄
I found this issue at work today so may as well solve it here too. When an error occurs in a gradle build script `projectsEvaluated(gradle: Gradle)` is never executed, meaning configuredTime = 0 and the configuration duration estimate will be 0-startTimeStamp.
To fix this, when the value is null we can assume the configuration phase failed so we use the currentTime instead.
You can test this by adding `throw new Exception()` into a project's `build.gradle` file and printing `configuredTime` both before and after this change by running `./gradlew help`
=> Fix configuredTime when configuration error

.github/workflows/build.yml
- Reverts jraska/github-client#692
- https://github.com/jraska/github-client/issues/705
This is the problem - duplicated jobs:
=> Revert "Add pull_request_target on build to be triggered from forked repos"

feature/performance/build.gradle, feature/performance/src/main/java/com/jraska/github/client/performance/PerformanceModule.kt, feature/performance/src/main/java/com/jraska/github/client/performance/jank/JankAnalyticsReporter.kt, feature/performance/src/main/java/com/jraska/github/client/performance/jank/JankMetric.kt
- Resolves #752 
- Analytics event is reported on 3+ frames missed
- Let's see how we perform in production
=> Add Jank performance measurement

plugins/src/main/java/com/jraska/github/client/firebase/report/FirebaseUrlParser.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseUrlParserTest.kt
- Firebase added space the search regex was not accounting for
- Before `[https://url]`, now `[ https://url ]`
- Both formats are now supported.
=> Update Firebase URL parser

core/src/main/java/com/jraska/github/client/http/HttpModule.kt, feature/identity/build.gradle, feature/identity/src/main/java/com/jraska/github/client/identity/IdentityModule.kt, feature/identity/src/main/java/com/jraska/github/client/identity/internal/AddSessionIdInterceptor.kt
- Added `Session-Id` header from the `:identity` module
- added `@IntoSet` composition for OkHttp interceptors
=> Add session id to network requests

feature/identity-api/src/main/java/com/jraska/github/client/identity/IntegrityTrigger.kt, feature/identity/build.gradle, feature/identity/src/main/java/com/jraska/github/client/identity/IdentityModule.kt, feature/identity/src/main/java/com/jraska/github/client/identity/integrity/IntegrityCheck.kt, feature/identity/src/main/java/com/jraska/github/client/identity/integrity/IntegrityCheckPushCommand.kt, feature/settings/build.gradle, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsViewModel.kt
- Integrity check can be triggered by push now
=> Integrity check to identity

app/build.gradle
- it was theoretically possible to link API modules 
- Explicitly restricted also to have restricted rules demonstration
=> Disallow API modules dependency

.github/workflows/build.yml
=> Generic build to build-check-unit-tests to be more explicit

core/src/main/java/com/jraska/github/client/http/ClientThrottlingInterceptor.kt, core/src/main/java/com/jraska/github/client/http/HttpModule.kt, core/src/test/java/com/jraska/github/client/http/ClientThrottlingInterceptorTest.kt, core/src/test/java/com/jraska/github/client/http/RequestRejectionRegistryTest.kt
- Resolves #825 
- https://sre.google/sre-book/handling-overload/
Client throttling not even reaching network:
=> Add client side throttling

core/src/test/java/com/jraska/github/client/http/ErrorLoggingConverterFactoryTest.kt
- case when backend changes data type of a field in an incompatible way
=> Add test for wrong JSON type

core-android-api/src/main/AndroidManifest.xml, core-android-testing/src/main/AndroidManifest.xml, core-testing/src/main/AndroidManifest.xml, feature/chrome-custom-tabs/src/main/AndroidManifest.xml, feature/config-debug/src/main/AndroidManifest.xml, feature/identity-api/src/main/AndroidManifest.xml, feature/identity/src/main/AndroidManifest.xml, feature/in-app-update/src/main/AndroidManifest.xml, feature/performance/src/main/AndroidManifest.xml, feature/ui-common-api/src/main/AndroidManifest.xml
Apparently we don't need the empty files anymore
=> Remove unused manifests

gradle.properties
- Default changed by the Android 8 plugin? https://developer.android.com/build/releases/gradle-plugin
- https://r8.googlesource.com/r8/+/refs/heads/master/compatibility-faq.md#r8-full-mode
- Related PR: https://github.com/jraska/github-client/issues/873
=> Disable R8 full mode

app/proguard-rules.pro, gradle.properties
- Resolves #873 
- Removing the `gradle.properties` configuration to rely on default
=> Enable R8 full mode

core/src/main/java/com/jraska/github/client/http/HttpModule.kt, core/src/main/java/com/jraska/github/client/http/HttpTrackingInterceptor.kt, core/src/main/java/com/jraska/github/client/http/NetworkResource.kt, core/src/main/java/com/jraska/github/client/http/NetworkResourceReporter.kt
- Simple version of network tracking as events to play with BigQuery as network requests tracker
=> Add debug network tracking

core/src/main/java/com/jraska/github/client/http/NetworkResourceReporter.kt, core/src/test/java/com/jraska/github/client/http/HttpTrackingInterceptorTest.kt
- Firebase reports errors with dots in the parameters names
=> Switch to underscores

core/src/main/java/com/jraska/github/client/http/ErrorLoggingConverterFactory.kt, core/src/main/java/com/jraska/github/client/http/MethodInfo.kt, core/src/main/java/com/jraska/github/client/http/ReportingConvertErrorHandler.kt, core/src/test/java/com/jraska/github/client/http/ErrorLoggingConverterFactoryTest.kt
- Example how to extract Retrofit information
- If we would have Observability, we would need to edit the paths in our Observability Collector
=> Add method info to parsing errors

core/src/main/java/com/jraska/github/client/http/ErrorLoggingConverterFactory.kt, core/src/main/java/com/jraska/github/client/http/HttpModule.kt, core/src/main/java/com/jraska/github/client/http/ReportingConvertErrorHandler.kt
- [Complexity Strikes Back by Hadi Hariri](https://www.droidcon.com/2022/11/18/keynote-the-silver-bullet-syndrome-directors-cut-complexity-strikes-back/) time `37:45`
- `ConvertErrorHandler` had always a single implementation and wasn't used across modules
- The test is an integration one, therefore no change was required
- Indirection, extra interface and Dagger binding removed.
- I got tired of modifying multiple places due to iterations on the interface.
- We can always refactor interface out if necessary
=> Remove unnecessary ConvertErrorHandler interface

app/build.gradle
It was huge part of the app - unused.
```
Total app size diff: 
Download: -432.42 kB, Install: -438.67 kB
----------------------------------------------Removed-----------------------------------------------
- com.github.bumptech.glide:glide:4.11.0 Download: 75.21 kB, Install: 75.5 kB
- io.grpc:grpc-core:1.52.1 Download: 65.68 kB, Install: 65.94 kB
- io.reactivex.rxjava2:rxjava:2.1.14 Download: 54.34 kB, Install: 54.56 kB
- com.google.protobuf:protobuf-javalite:3.21.7 Download: 51.63 kB, Install: 51.83 kB
- com.google.firebase:firebase-inappmessaging:20.3.3 Download: 39.09 kB, Install: 39.23 kB
- io.grpc:grpc-okhttp:1.52.1 Download: 32.5 kB, Install: 32.63 kB
- io.grpc:grpc-api:1.52.1 Download: 21.98 kB, Install: 22.07 kB
- com.google.firebase:firebase-inappmessaging-display:20.3.3 …
```
=> Remove Firebase In App Messaging

feature/chrome-custom-tabs/build.gradle, feature/chrome-custom-tabs/src/main/java/com/jraska/github/client/chrome/ChromeCustomTabsLauncher.kt, feature/chrome-custom-tabs/src/main/java/com/jraska/github/client/chrome/ChromeCustomTabsModule.kt
- The logic was required to stop the app itself appearing years ago - this is no longer happening
- It introduced complexity and crashes
- 🔥 🔥 🔥
=> Remove custom link launcher logic
