jraska/github-client

client-data/src/main/java/com/jraska/github/client/rx/RxLiveData.java, client-data/src/main/java/com/jraska/github/client/users/UserDetailViewModel.java, client-data/src/main/java/com/jraska/github/client/users/UsersViewModel.java, client/src/main/java/com/jraska/github/client/ui/UserDetailActivity.java, client/src/main/java/com/jraska/github/client/ui/UsersActivity.java
Polymorphism with `apply` function will be more powerful, but this is enough as example usage
=> Trivial ViewState pattern

client/src/main/java/com/jraska/github/client/AppModule.java, client/src/main/java/com/jraska/github/client/GitHubClientApp.java, client/src/test/java/com/jraska/github/client/ViewModelFactoryDecorator.java, client/src/test/java/com/jraska/github/client/ui/RepoDetailActivityTest.java
Resolves #21 
We use simple decoration to provide custom ViewModel for Activity
=> Robolectric with ViewModel injection

client-data/build.gradle, client/build.gradle, client/src/main/AndroidManifest.xml, client/src/main/java/com/google/firebase/messaging/RemoteMessageBridge.java, client/src/main/java/com/jraska/github/client/GitHubClientApp.java, client/src/main/java/com/jraska/github/client/push/PushAction.java, client/src/main/java/com/jraska/github/client/push/PushCallbacks.java, client/src/main/java/com/jraska/github/client/push/PushHandleService.java, client/src/main/java/com/jraska/github/client/push/PushHandler.java, client/src/main/java/com/jraska/github/client/push/PushIntentObserver.java, client/src/main/java/com/jraska/github/client/push/RemoteMessageToActionConverter.java
=> 26 enable push

client-domain/src/main/java/com/jraska/github/client/Config.java, client/src/main/java/com/jraska/github/client/FirebaseConfigProxy.java, client/src/main/java/com/jraska/github/client/push/PushHandler.java
=> Refresh config by push

client/src/main/AndroidManifest.xml, client/src/main/java/com/jraska/github/client/NavigationModule.java, client/src/main/java/com/jraska/github/client/ui/ShortcutHandlerActivity.java, client/src/main/java/com/jraska/github/client/ui/ShortcutHandlerModel.java, client/src/main/res/values/strings.xml, client/src/main/res/xml/shortcuts.xml
=> #32 Implement demo app shortcuts

client-data/src/main/java/com/jraska/github/client/users/UserDetailViewModel.java, client-data/src/main/java/com/jraska/github/client/users/UserViewModelModule.java, client-data/src/main/java/com/jraska/github/client/users/data/GitHubApiUsersRepository.java, client-data/src/main/java/com/jraska/github/client/users/data/UserDetailWithReposConverter.java, client-data/src/test/java/com/jraska/github/client/FakeConfig.java, client-data/src/test/java/com/jraska/github/client/users/UserDetailViewModelTest.java, client-domain/src/main/java/com/jraska/github/client/Config.java, client-domain/src/main/java/com/jraska/github/client/users/UsersRepository.java, client/src/main/java/com/jraska/github/client/FirebaseConfigProxy.java, client/src/main/java/com/jraska/github/client/FirebaseModule.java, client/src/main/res/xml/config_defaults.xml
=> Configure user detail repos count

client/src/test/java/com/jraska/github/client/TestGitHubClientApp.java, client/src/test/resources/robolectric.properties
=> Fix flakey robolecric tests

client-domain/src/main/java/com/jraska/github/client/time/DateTimeProvider.java, client-domain/src/main/java/com/jraska/github/client/time/RealDateTimeProvider.java, client/src/main/java/com/jraska/github/client/AppModule.java, client/src/main/java/com/jraska/github/client/push/PushHandler.java, client/src/main/java/com/jraska/github/client/push/PushTokenSynchronizer.java
=> Device info next to push token

client-data/src/test/java/com/jraska/github/client/FakeConfig.java, client-domain/src/main/java/com/jraska/github/client/Config.java, client-domain/src/main/java/com/jraska/github/client/analytics/AnalyticsProperty.java, client-domain/src/main/java/com/jraska/github/client/common/Lists.java, client-domain/src/main/java/com/jraska/github/client/common/Maps.java, client/src/main/AndroidManifest.xml, client/src/main/java/com/jraska/github/client/FirebaseConfigProxy.java, client/src/main/java/com/jraska/github/client/FirebaseEventAnalytics.java, client/src/main/java/com/jraska/github/client/FirebaseModule.java, client/src/main/java/com/jraska/github/client/push/PushAction.java, client/src/main/java/com/jraska/github/client/push/PushHandler.java, client/src/main/java/com/jraska/github/client/push/RemoteMessageToActionConverter.java, client/src/test/java/com/jraska/github/client/FakeFirebaseModule.java, client/src/test/java/com/jraska/github/client/push/RemoteMessageToActionConverterTest.java
=> Setting properties by push

build.gradle, client/build.gradle
Resolves #67 and is related to #68
=> Setup crashlytics

client/src/androidTest/java/com/jraska/github/client/FakeCoreComponent.kt, client/src/androidTest/java/com/jraska/github/client/TestUITestApp.kt, client/src/main/java/com/jraska/github/client/AppComponent.kt, client/src/main/java/com/jraska/github/client/CoreComponent.kt, client/src/main/java/com/jraska/github/client/FirebaseModule.kt, client/src/main/java/com/jraska/github/client/GitHubClientApp.kt
Just create bridging module :)
=> Multiple inheritance with Dagger components solution

client/src/main/java/com/jraska/github/client/AppModule.kt, client/src/main/java/com/jraska/github/client/GitHubClientApp.kt, client/src/main/java/com/jraska/github/client/NotificationSetup.kt, client/src/main/java/com/jraska/github/client/push/PushHandler.kt, client/src/main/res/values/strings.xml
=> Push notification display

client-data/src/main/java/com/jraska/github/client/users/data/RepoConverter.kt, client-data/src/main/java/com/jraska/github/client/users/data/UserDetailWithReposConverter.kt, client-data/src/test/java/com/jraska/github/client/users/UserDetailViewModelTest.kt, client-domain/src/main/java/com/jraska/github/client/time/DateTimeProvider.kt, client-domain/src/main/java/com/jraska/github/client/time/RealDateTimeProvider.kt, client-domain/src/main/java/com/jraska/github/client/users/RepoDetail.kt, client-domain/src/main/java/com/jraska/github/client/users/UserStats.kt, client/src/main/java/com/jraska/github/client/ui/RepoDetailHeaderModel.kt, client/src/main/java/com/jraska/github/client/ui/UserHeaderModel.kt
=> Use Instant everywhere

client-data/build.gradle, client-data/src/main/java/com/jraska/github/client/AnalyticsLoggingTree.kt, client-domain/src/main/java/com/jraska/github/client/analytics/AnalyticsEvent.kt, client/build.gradle, client/src/main/java/com/jraska/github/client/FirebaseModule.kt, client/src/main/java/com/jraska/github/client/GitHubClientApp.kt
=> Add analytics debugging

.circleci/config.yml
=> All test results to CI reports

client/build.gradle
=> Disable Firebase performance plugin

feature-push/src/main/java/com/jraska/github/client/push/ShowNotificationPushCommand.kt
=> Add missiing small icon

client/src/main/AndroidManifest.xml, client/src/main/res/xml/shortcuts.xml, core-android/src/main/java/com/jraska/github/client/core/android/Activity.kt
=> Have shortcuts handled by custom scheme instead of package name

client/src/main/java/com/jraska/github/client/http/HttpModule.kt, feature-about/src/main/java/com/jraska/github/client/about/IconModel.kt, lib-identity/src/main/java/com/jraska/github/client/identity/IdentityProvider.kt
=> Styling fixes

client/src/main/java/com/jraska/github/client/AppComponent.kt, client/src/main/java/com/jraska/github/client/GitHubClientApp.kt
Use delegate modules and Dagger dependencies instead of delegating each method manually
=> Simplify Dagger setup

privacy_policy.md
Even testing app apparently needs privacy policy 🙄
=> Add privacy policy

feature/about/src/main/java/com/jraska/github/client/about/AboutFeature.kt, feature/about_entrance/src/main/java/com/jraska/github/client/about/entrance/AboutFeatureEntranceModule.kt, feature/about_entrance/src/main/java/com/jraska/github/client/about/entrance/internal/ReflectiveAboutFeatureProvider.kt, lib-dynamic-features/src/main/java/com/jraska/github/client/dynamicbase/DynamicFeature.kt, lib-dynamic-features/src/main/java/com/jraska/github/client/dynamicbase/DynamicFeatureSpec.kt, lib-dynamic-features/src/main/java/com/jraska/github/client/dynamicbase/DynamicFeaturesModule.kt, lib-dynamic-features/src/main/java/com/jraska/github/client/dynamicbase/internal/DynamicFeatureInitializer.kt
- Added `DynamicFeature` interface to have umbrella for dynamically loaded classes
- Prerequisite for #172
=> Add dynamic feature loading

gradle.properties
=> Enable incremental kapt

build.gradle
=> Update AGP to 3.5.1 and Kotlin to 1.3.50

app/build.gradle, app/src/androidTest/java/com/jraska/github/client/TestRunner.kt, app/src/androidTest/java/com/jraska/github/client/users/UsersActivityFlowTest.kt, feature/about/build.gradle, feature/settings/build.gradle, lib/dynamic-features/build.gradle
- Added RxIdler to make sure latency is not a problem
- removed `api` as they bring problems - be explicit!
- Resolves #199 as now everything works
=> Shuffle dependencies to make Instrumented tests working

build.gradle, buildSrc/build.gradle, buildSrc/src/main/java/com/jraska/github/client/AssertModuleTreeHeight.kt, buildSrc/src/main/java/com/jraska/github/client/DependencyTree.kt, buildSrc/src/main/java/com/jraska/github/client/DependencyTreeFactory.kt, buildSrc/src/main/java/com/jraska/github/client/GenerateProjectsGraphTask.kt
- max height of tree from app is now 4
- Resolves #193
=> Add graph visualisation and measurement

buildSrc/build.gradle, buildSrc/src/main/java/com/jraska/github/client/AssertModuleTreeHeight.kt, buildSrc/src/main/java/com/jraska/github/client/DependencyTree.kt, buildSrc/src/main/java/com/jraska/github/client/GenerateProjectsGraphTask.kt, buildSrc/src/main/java/com/jraska/github/client/GraphvizGenerator.kt, buildSrc/src/main/java/com/jraska/github/client/LongestPath.kt, buildSrc/src/test/java/com/jraska/github/client/DependencyTreeTest.kt
=> Displaying longest path

build.gradle, buildSrc/src/main/java/com/jraska/github/client/AssertModuleTreeHeightTask.kt, buildSrc/src/main/java/com/jraska/github/client/DependencyTree.kt, buildSrc/src/main/java/com/jraska/github/client/GenerateModulesGraphTask.kt, buildSrc/src/main/java/com/jraska/github/client/GenerateOneModuleGraphTask.kt, buildSrc/src/main/java/com/jraska/github/client/GraphStatistics.kt, buildSrc/src/test/java/com/jraska/github/client/DependencyTreeTest.kt
- Edges count
- Nodes count
- Height of the graph
=> Add counting basic statistics

README.md
Let's give a visitor at least a rough guidace
=> Update README.md with topics in this repo

app/build.gradle, build.gradle, buildSrc/src/main/java/com/jraska/github/client/AssertCrossLayerDependencies.kt, buildSrc/src/main/java/com/jraska/github/client/AssertInLayerDependencies.kt, buildSrc/src/main/java/com/jraska/github/client/DependencyGraph.kt, buildSrc/src/main/java/com/jraska/github/client/DependencyTreeFactory.kt, buildSrc/src/main/java/com/jraska/github/client/GenerateModulesGraphTask.kt, buildSrc/src/main/java/com/jraska/github/client/GraphStatistics.kt, buildSrc/src/main/java/com/jraska/github/client/GraphvizGenerator.kt, buildSrc/src/test/java/com/jraska/github/client/DependencyGraphTest.kt, gradle/wrapper/gradle-wrapper.properties
- Assert no dependencies between features
- Assert no dependencies against layer hierarchy
- Draw dependency graph with layers
=> Add layers highlighting and layers assertions

app/build.gradle, build.gradle, core-testing/build.gradle, core/build.gradle, feature/about_entrance/build.gradle, feature/push/build.gradle, feature/settings_entrance/build.gradle, feature/shortcuts/build.gradle, feature/users/build.gradle, lib/identity/build.gradle, lib/navigation-deeplink/build.gradle, lib/network-status/build.gradle, navigation/build.gradle
identity and navigation-deeplink are now `java-library`
some `api` replaced by `implementation`
=> Make some module jvm modules

.circleci/config.yml, app-partial-users/build.gradle, app/build.gradle, build.gradle, core-android/build.gradle, core/build.gradle, feature/about/build.gradle, feature/about_entrance/build.gradle, feature/push/build.gradle, feature/push/src/main/java/com/jraska/github/client/push/PushHandleModel.kt, feature/push/src/main/java/com/jraska/github/client/push/PushHandleService.kt, feature/push/src/main/java/com/jraska/github/client/push/PushHandler.kt, feature/push/src/main/java/com/jraska/github/client/push/PushTokenSynchronizer.kt, feature/settings/build.gradle, feature/settings_entrance/build.gradle, feature/shortcuts/build.gradle, feature/users/build.gradle, gradle.properties, lib/dynamic-features/build.gradle, lib/identity/build.gradle, lib/navigation-deeplink/build.gradle, lib/network-status/build.gradle
- one exception play-crore - there is some resource linking issue
=> Update All libraries to latest version

app-partial-users/src/main/java/com/jraska/github/client/users/UsersAppComponent.kt, app/src/main/java/com/jraska/github/client/AppComponent.kt, app/src/main/java/com/jraska/github/client/AppModule.kt, app/src/main/java/com/jraska/github/client/http/Http.kt, app/src/main/java/com/jraska/github/client/http/HttpComponent.kt, app/src/main/java/com/jraska/github/client/http/HttpModule.kt, core-android/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt, core/src/main/java/com/jraska/github/client/PerApp.kt, feature/push/src/main/java/com/jraska/github/client/push/PushModule.kt, feature/users/src/main/java/com/jraska/github/client/users/UsersModule.kt, lib/dynamic-features/src/main/java/com/jraska/github/client/dynamicbase/DynamicFeaturesModule.kt, lib/identity/src/main/java/com/jraska/github/client/identity/IdentityModule.kt
- Singleton can be used for everything if we properly define component dependencies with non-`@Component` interface
=> Remove custom DI scopes

app/build.gradle, app/src/androidTest/java/com/jraska/github/client/http/OkReplayMediator.kt, app/src/androidTest/java/com/jraska/github/client/http/ReplayHttpComponent.kt
=> Update OkReplay and use mediator instead of inheritance

build.gradle, feature/about/src/main/AndroidManifest.xml, feature/settings/src/main/AndroidManifest.xml
=> Update AGP, Kotlin

.circleci/config.yml, app/firebase-test-lab.gradle
- Using gsutil and specified --results-dir parameter to pull the latest xml
=> Pulling firebase results

README.md, app/build.gradle, build.gradle
=> Add tripleT plugin for publishing to Google Play from Gradle

app/src/androidTest/java/com/jraska/github/client/AppSetupTest.kt, app/src/androidTest/java/com/jraska/github/client/users/UsersActivityFlowTest.kt, app/src/main/java/com/jraska/github/client/GitHubClientApp.kt
- some checks verifying app setup logic
=> Add AppSetupTest

app-partial-users/build.gradle, app/build.gradle, build.gradle, core/build.gradle, feature/users/build.gradle, navigation/build.gradle
- Let's see of Dependabot can handle it :)
=> Move retrofit and Okhttp versions into ext property

build.gradle, dependencies.gradle
- let's try what can dependabot see
=> Retrofit into separate Gradle file

app-partial-users/build.gradle, app/build.gradle, build.gradle, feature/about/build.gradle, feature/users/build.gradle, lib/network-status/build.gradle
- Remove mockito-android dependency
- Unify Dager and Fresco dependencies
- Few other minor updates
=> Dependencies updates

.github/dependabot.yml
=> Update dependabot interval to weekly checks

.circleci/config.yml
All parallel was causing troubles, let's try a bit parallel.
=> Try max workers=2 on CI

app/build.gradle, app/src/main/java/com/jraska/github/client/logging/FirebaseCrashlyticsProxy.kt, feature/push/build.gradle
- Use BOM dependency for Firebase stuff
- `com.crashlytics` -> `com.google.firebase.crashlytics`
=> Update Crashlytics SDK

app/build.gradle, plugins/build.gradle, plugins/src/main/java/com/jraska/module/GradleStatisticsReportProcess.kt, plugins/src/main/java/com/jraska/module/ModuleStatistics.kt, plugins/src/main/java/com/jraska/module/ModuleStatsPlugin.kt, plugins/src/main/java/com/jraska/module/ModuleStatsReporter.kt, plugins/src/main/java/com/jraska/module/extract/StatisticsGradleExtractor.kt, plugins/src/main/java/com/jraska/module/report/ConsoleReporter.kt, plugins/src/main/java/com/jraska/module/report/MixpanelModuleStatsReporter.kt
=> Add reporting of modules statistics

app/src/androidTest/java/com/jraska/github/client/settings/SettingsTest.kt, feature/navigation-deeplink/src/main/java/com/jraska/github/client/navigation/deeplink/internal/DeepLinkNavigator.kt, feature/settings/build.gradle, feature/settings/src/main/AndroidManifest.xml, feature/settings/src/main/java/com/jraska/github/client/settings/ConsoleActivity.kt, feature/settings/src/main/java/com/jraska/github/client/settings/ConsoleModel.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsActivity.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsLinkLauncher.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsViewModel.kt, feature/settings/src/main/res/layout/item_row_console.xml, navigation-api/src/main/java/com/jraska/github/client/navigation/Navigator.kt, navigation-api/src/main/java/com/jraska/github/client/navigation/Urls.kt
Have an activity which shows scrollable fullscreen console
=> Add fullscreen console

.circleci/config.yml
=> Add scheduled module statistics reporting

.circleci/config.yml, app/src/androidTest/java/com/jraska/github/client/settings/SettingsTest.kt
- Gradle recommends that, we just need to limit the workers see: https://circleci.com/docs/2.0/language-java/
=> Use Daemon with 2 workers

plugins/src/main/java/com/jraska/gradle/buildtime/report/MixpanelReporter.kt
=> Handle reporting failures properly

feature/users/src/main/java/com/jraska/github/client/users/UserDetailViewModel.kt, feature/users/src/main/java/com/jraska/github/client/users/UsersViewModel.kt, feature/users/src/main/java/com/jraska/github/client/users/model/RepoDetailViewModel.kt
=> Remove casting warnings

plugins/src/main/java/com/jraska/github/client/firebase/report/FirebaseResultExtractor.kt
To be able to filter by `is not set` on Mixpanel
=> Do not set failure

.circleci/config.yml, plugins/src/main/java/com/jraska/github/client/firebase/Device.kt, plugins/src/main/java/com/jraska/github/client/firebase/FirebaseTestLabPlugin.kt, plugins/src/main/java/com/jraska/github/client/firebase/report/FirebaseResultExtractor.kt
Virtual devices were problematic with push, but also way slower to execute. Even slower fo processing the outputs.
=> Add Pixel 2 device

plugins/build.gradle
=> Update Kotlin in plugins directory

feature/about/build.gradle, feature/settings/build.gradle
- Lint found some missing stuff
=> Add missing dependencies

.circleci/config.yml, app/build.gradle, build.gradle, core-api/build.gradle, core-testing/build.gradle, feature/config-debug-api/build.gradle, feature/identity-api/build.gradle, feature/identity/build.gradle, feature/navigation-deeplink/build.gradle, plugins/build.gradle, plugins/src/main/java/com/jraska/lint/LintAnalyticsReporter.kt, plugins/src/main/java/com/jraska/lint/LintIssue.kt, plugins/src/main/java/com/jraska/lint/LintProjectExtractor.kt, plugins/src/main/java/com/jraska/lint/LintReportProcess.kt, plugins/src/main/java/com/jraska/lint/LintReporterPlugin.kt, plugins/src/main/java/com/jraska/lint/LintXmlParser.kt, plugins/src/main/java/com/jraska/module/ModuleMetadata.kt, plugins/src/main/java/com/jraska/module/ModuleStatistics.kt, plugins/src/main/java/com/jraska/module/ModuleStatsReporter.kt, plugins/src/main/java/com/jraska/module/extract/StatisticsGradleExtractor.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseResultExtractorTest.kt, plugins/src/test/kotlin/com/jraska/lint/LintXmlParserTest.kt
- Resolves #361 
- Will report lint outputs periodically
=> Report lint issues

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/config-debug/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/push/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/users/build.gradle, plugins/src/test/kotlin/com/jraska/github/client/release/VersionIncrementTest.kt
- Let's drop Android 6
- https://developer.android.com/studio/releases/platforms#7.0
=> Update minSdk=24 - Android 7.0

app-partial-users/build.gradle, app/build.gradle, core-api/build.gradle, navigation-api/build.gradle, plugins/build.gradle
https://medium.com/@mbonnin/the-different-kotlin-stdlibs-explained-83d7c6bf293
=> Use only stdlib without anything special on JDK

core-android-api/build.gradle
- should be enforced next time
=> Remove unused kapt in API module

app/src/main/java/com/jraska/github/client/FirebaseCoreModule.kt, feature/repo/src/main/java/com/jraska/github/client/repo/model/GitHubRepo.kt
- Small tweak to trigger CI
- Remove unused fields
=> Config key visibility to private, remove some unused fields

gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/6.8.3/release-notes.html
=> Update Gradle to 6.8.3

core-api/src/main/java/com/jraska/github/client/common/DeveloperError.kt, core/src/main/java/com/jraska/github/client/core/android/logging/ErrorReportTree.kt
=> Move Developer error to ErrorReportTree

.github/workflows/release.yml
=> Add release test step

app/build.gradle
- GITHUB* prefixes do not work
=> Rename GITHUB env vars as GitHub is complaining for secrets

.github/workflows/release.yml, app/build.gradle
- Added publishRelease and env vars
=> Publish release from GitHub actions

build.gradle, dependencies.gradle
- To share with composite builds
=> Move stuff to dependencies.gradle

app/build.gradle, plugins/src/main/java/com/jraska/github/client/release/Environment.kt, plugins/src/main/java/com/jraska/github/client/release/ReleaseMarksPRs.kt, plugins/src/main/java/com/jraska/github/client/release/data/GitHubApiFactory.kt
- Marking Release failed from some reason - let's see what had happen.
=> Add proper logging to see the errors

.github/workflows/release_trigger.yml, plugins/src/main/java/com/jraska/github/client/release/CreateReleaseAndBump.kt, plugins/src/main/java/com/jraska/github/client/release/GitHubApi.kt, plugins/src/main/java/com/jraska/github/client/release/GradleFileUtils.kt, plugins/src/main/java/com/jraska/github/client/release/ReleasePlugin.kt, plugins/src/main/java/com/jraska/github/client/release/data/GitHubApiImpl.kt, plugins/src/main/java/com/jraska/github/client/release/data/RetrofitGitHubApi.kt, plugins/src/test/kotlin/com/jraska/github/client/release/GradleFileUtilsTest.kt
=> Create release through API to trigger Workflows

app/src/androidTest/java/com/jraska/github/client/DeepLinkLaunchTest.kt
- Got there by accident -= the tests should work just fine without it
=> Remove accidental Thread.sleep

plugins/src/main/java/com/jraska/github/client/firebase/FirebaseTestLabPlugin.kt, plugins/src/main/java/com/jraska/github/client/firebase/TestSuiteResult.kt, plugins/src/main/java/com/jraska/github/client/firebase/report/FirebaseResultExtractor.kt, plugins/src/main/java/com/jraska/github/client/firebase/report/TestResultsReporter.kt, plugins/src/main/java/com/jraska/gradle/CiInfo.kt, plugins/src/main/java/com/jraska/gradle/buildtime/BuildData.kt, plugins/src/main/java/com/jraska/gradle/buildtime/BuildDataFactory.kt, plugins/src/main/java/com/jraska/gradle/buildtime/BuildReporter.kt
=> Add GitHub actions metadata to build time and tests

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/release_trigger.yml, .github/workflows/reporting.yml, feature/users/src/main/java/com/jraska/github/client/users/model/User.kt
- Use top level instead of copy paste all the time.
=> Share env vars

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-api/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/identity/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/users/build.gradle
- All dependencies have to be explicit
- Comparison of dependencies coming tomorrow
=> Remove api dependencies

app/build.gradle
- The task `uploadCrashlyticsMappingFileRelease`
- https://github.com/Triple-T/gradle-play-publisher/issues/859
=> Try to upload Firebase mapping

core-api/src/main/java/com/jraska/github/client/ui/SnackbarDisplay.kt, core/build.gradle, core/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt, core/src/main/java/com/jraska/github/client/users/widget/TopSnackbarDisplay.kt, feature/in-app-update/src/main/java/com/jraska/github/client/inappupdate/UpdateChecker.kt, feature/repo/src/main/java/com/jraska/github/client/repo/RepoDetailViewModel.kt, feature/repo/src/test/java/com/jraska/github/client/repo/RepoDetailViewModelTest.kt, feature/users/src/main/java/com/jraska/github/client/users/UsersModule.kt
- We should be able to fake it :)
=> Move SnackbarDisplay to core-api as pure JVM interface

app/src/androidTest/java/com/jraska/github/client/DeepLinkLaunchTest.kt, app/src/androidTest/java/com/jraska/github/client/settings/SettingsTest.kt, app/src/androidTest/java/com/jraska/github/client/users/UsersActivityFlowTest.kt, app/src/androidTest/java/com/jraska/github/client/xpush/PushIntegrationTest.kt, feature/config-debug/src/test/java/com/jraska/github/client/config/debug/MutableConfigTest.kt, feature/navigation-deeplink/src/test/java/com/jraska/github/client/navigation/deeplink/DeepLinkNavigatorTest.kt, feature/push/src/test/java/com/jraska/github/client/push/RemoteMessageToActionConverterTest.kt, feature/repo/src/test/java/com/jraska/github/client/repo/RepoDetailViewModelTest.kt, feature/users/src/test/java/com/jraska/github/client/users/UserDetailViewModelTest.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseResultExtractorTest.kt, plugins/src/test/kotlin/com/jraska/lint/LintXmlParserTest.kt
=> Rename tests to make Sonar happy

README.md
=> Add Lead Time to README

feature/config-debug/src/test/java/com/jraska/github/client/config/debug/MutableConfigTest.kt
=> Remove duplicated string

README.md
- cannot display ui yet
- Related to #436
=> Add Modules Instrumented tests into README

.github/workflows/build.yml, .github/workflows/reporting.yml, feature/users/src/main/java/com/jraska/github/client/users/ui/UsersActivity.kt, gradle/wrapper/gradle-wrapper.properties, plugins/src/main/java/com/jraska/gradle/buildtime/BuildDataFactory.kt, plugins/src/main/java/com/jraska/gradle/buildtime/BuildTimeListener.kt
- let's try the bin distribution
- https://docs.gradle.org/7.0/release-notes.html
=> Upgrade to Gradle 7.0

.github/workflows/build.yml, .github/workflows/reporting.yml
- split cache key for lint and the rest to achieve better cache hit
=> Cache key improvements

.github/workflows/build.yml, .github/workflows/reporting.yml
=> New hash keys 🤦 

app/build.gradle, feature/users/build.gradle, feature/users/src/androidTest/java/com/jraska/github/client/users/ui/ReposSectionModelTest.kt, feature/users/src/main/java/com/jraska/github/client/users/model/RepoHeader.kt, feature/users/src/main/java/com/jraska/github/client/users/ui/ReposSectionModel.kt
=> Add ReposSectionModelTest

feature/users/src/main/AndroidManifest.xml
- minor one liner to enable better UI tests
- related to #60
=> Add theme to users module

app/src/androidTest/java/com/jraska/github/client/TestUITestApp.kt, app/src/main/java/com/jraska/github/client/AppComponent.kt, app/src/main/java/com/jraska/github/client/GitHubClientApp.kt, core/src/main/java/com/jraska/github/client/core/android/AppBaseComponent.kt, core/src/main/java/com/jraska/github/client/core/android/BaseApp.kt
- Related to #436 
- I'm sure I will regret inheritance :P
=> Have a BaseApp to share the base component - should unify UI tests setup

app/src/androidTest/java/com/jraska/github/client/xpush/PushAwaitRule.kt, app/src/androidTest/java/com/jraska/github/client/xpush/PushIntegrationTest.kt, app/src/androidTest/java/com/jraska/github/client/xpush/PushServerClient.kt, feature/push/src/main/java/com/jraska/github/client/push/PushTokenSynchronizer.kt
- Remove deprecated API usage
- Naming improvements
- Simplifying
=> Improve push tests

README.md
- new module graph added
- testing section updated
=> Update README with testing updates

app/build.gradle
- following https://firebase.google.com/docs/in-app-messaging/get-started?authuser=0&platform=android
=> Add inappmessaging

app/build.gradle, build.gradle
=> Always enable Firebase performance on CI builds

app/src/main/java/com/jraska/github/client/GitHubClientApp.kt
- to see the impact of the app_start
=> Add onCreate traces

feature/users/src/main/java/com/jraska/github/client/users/ui/UsersActivity.kt
- New adapter kills the scroll position
=> Do not create always new Adapter to keep scroll position

feature/network-status/src/main/java/com/jraska/github/client/networkstatus/internal/NetworkObservable.kt
=> Make sure we get always up-to-date network state

build.gradle, dependencies.gradle
Fresco was the last dependency on JCenter
https://github.com/facebook/fresco/issues/2585
=> Update Fresco + remove Jcenter

app/build.gradle, core/build.gradle, core/src/test/java/com/jraska/github/client/core/android/TopActivityProviderImplTest.kt, feature/about/build.gradle, plugins/build.gradle
=> Remove Mockito + plugins update

build.gradle
- https://stackoverflow.com/questions/67865303/crashlytic-gradle-2-7-0-error-type-uploadmappingfiletask-property-googleser
- https://github.com/jraska/github-client/actions/runs/935115242
=> Downgrade crashlytics as there is an issue with release

app/src/main/java/com/jraska/github/client/FirebaseConfigProxy.kt
=> Use only zero for refreshing config

feature/push/src/main/java/com/jraska/github/client/push/PushHandleModelImpl.kt, feature/push/src/main/java/com/jraska/github/client/push/PushModule.kt, feature/push/src/main/java/com/jraska/github/client/push/PushTokenSynchronizer.kt, feature/push/src/main/java/com/jraska/github/client/push/SendPushTokenCommand.kt
- In case we clear the database - we can easily recover tokens
=> Add a push action to resend a push token

plugins/src/main/java/com/jraska/github/client/firebase/Device.kt, plugins/src/main/java/com/jraska/github/client/firebase/FirebaseTestLabPlugin.kt
- It is still worth running on two devices
- pixel 5 tried successfully as well, but opting for some lower API level for now
Current devices snapshot:
```
┌───────────────────┬────────────────────┬─────────────────────────────────────┬──────────┬─────────────┬─────────────────────────┬────────────────┐
│      MODEL_ID     │        MAKE        │              MODEL_NAME             │   FORM   │  RESOLUTION │      OS_VERSION_IDS     │      TAGS      │
├───────────────────┼────────────────────┼─────────────────────────────────────┼──────────┼─────────────┼─────────────────────────┼────────────────┤
│ 1725              │ Vivo               │ vivo 1725                           │ PHYSICAL │ 2280 x 1080 │ 27                      │                │
│ 1805              │ Vivo               │ vivo …
```
=> Use Firebase Pixel 2, API 27 device instead of deprecated API 28

.github/workflows/build.yml
=> Disable Firebase test lab

plugins/src/main/java/com/jraska/lint/LintProjectExtractor.kt
=> Update Lint results path

.github/workflows/build.yml, plugins/src/main/java/com/jraska/github/client/firebase/Device.kt, plugins/src/main/java/com/jraska/github/client/firebase/FirebaseTestLabPlugin.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseResultExtractorTest.kt
=> Enable back Firebase Test lab with Pixel 5 and Pixel 2

plugins/src/main/java/com/jraska/analytics/AnalyticsReporter.kt, plugins/src/main/java/com/jraska/analytics/ConsoleReporter.kt, plugins/src/main/java/com/jraska/analytics/MixpanelAnalyticsReporter.kt, plugins/src/main/java/com/jraska/gradle/buildtime/BuildReporter.kt, plugins/src/main/java/com/jraska/module/ModuleStatsReporter.kt, plugins/src/test/kotlin/com/jraska/github/client/release/data/LeadTimeReporterTest.kt
=> Analytics improvements

.github/workflows/build.yml, app/build.gradle, settings.gradle
- Add remote cache with push on CI
- Only dependencies are cached now for the GitHub actions cache
- Local cache disabled on CI
=> Have running remote cache

core-api/src/main/java/com/jraska/github/client/rx/AppSchedulers.kt
=> Remove unused empty method

app-partial-users/src/main/AndroidManifest.xml, app/src/main/AndroidManifest.xml, core/src/main/AndroidManifest.xml, feature/push/src/main/AndroidManifest.xml, feature/push/src/main/java/com/jraska/github/client/push/ShowNotificationCommand.kt, feature/shortcuts/src/main/AndroidManifest.xml
https://developer.android.com/about/versions/12/behavior-changes-all
=> Setting exported property + intent flags for Android 12

app/src/androidTest/java/com/jraska/github/client/espressox/LongClickPatch.kt, app/src/androidTest/java/com/jraska/github/client/users/UsersActivityFlowTest.kt
Happen several times recently: https://issuetracker.google.com/issues/37078920
- https://github.com/jraska/github-client/runs/3315880917?check_suite_focus=true
=> Add no-op long click revert action

core-api/build.gradle, core/build.gradle, feature/identity/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/users/build.gradle
Not sure why dependabot does not pick this up
=> Bump threetenbp to 1.5.1

core-api/src/main/java/com/jraska/github/client/Owner.kt, core/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt, core/src/main/java/com/jraska/github/client/startup/AppStartupModule.kt, core/src/main/java/com/jraska/github/client/startup/StartupAnalyticsReporter.kt, core/src/main/java/com/jraska/github/client/startup/StartupTimeMetric.kt
- First version to get some production data.
- Most ifno got from here: https://dev.to/pyricau/android-vitals-why-did-my-process-start-4d0e
=> Add launch time reporting

app/build.gradle
- StackOverflow rules the development :D https://stackoverflow.com/questions/67865303/type-uploadmappingfiletask-property-googleservicesresourceroot-doesnt-have
- Failed release: https://github.com/jraska/github-client/actions/runs/1408414082
=> Move Google Play Services on top of Firebase plugins

gradle/wrapper/gradle-wrapper.properties, plugins/gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/7.3.3/release-notes.html
=> Gradle to 7.3.3

gradle/wrapper/gradle-wrapper.properties, plugins/gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/current/release-notes.html
=> Gradle 7.4

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-android-testing/build.gradle, core-testing/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/config-debug/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/push/build.gradle, feature/push/src/main/java/com/jraska/github/client/push/NotificationSetup.kt, feature/repo/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/ui-common-api/build.gradle, feature/users/build.gradle
- https://developer.android.com/about/versions/oreo/android-8.0
- https://developer.android.com/about/versions/oreo/android-8.0-changes
- https://developer.android.com/about/versions/nougat/android-7.1
=> Min SDK to 26

build.gradle, plugins/build.gradle
Kotlin and assertj were separate in composite builds
=> Bump Google-services to 4.3.10 + aligning composite build versions

gradle.properties
https://youtrack.jetbrains.com/issue/KT-48826
=> kapt.use.worker.api removed

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-android-testing/build.gradle, core-testing/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/config-debug/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/ui-common-api/build.gradle, feature/users/build.gradle, settings.gradle
- [Docs](https://developer.android.com/about/versions/13)
- Possibly issues with notifications https://github.com/jraska/github-client/issues/748
=> Android 13

app/build.gradle
- set `assertOnAnyBuild = true` for immediate feedback
=> Bump module-graph-assert plugin to version 2.3.0

feature/about/src/main/java/com/jraska/github/client/about/AboutModule.kt
- this change will break master branch - we will revert it soon to demonstrate MTTR
=> Breaking master change to demonstrate CI metrics

feature/about/src/main/java/com/jraska/github/client/about/AboutModule.kt
Reverts jraska/github-client#755
=> Revert "Breaking master change to demonstrate CI metrics"

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-android-testing/build.gradle, core-testing/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/config-debug/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/performance/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/ui-common-api/build.gradle, feature/users/build.gradle
- Related to #749 - I messed up and considered a wrong API level - we aim for 33.
=> Android 13 - API 33

build.gradle, gradle/wrapper/gradle-wrapper.properties, plugins/gradle/wrapper/gradle-wrapper.properties
- [7.5.1 release notes](https://docs.gradle.org/7.5.1/release-notes.html)
=> Gradle 7.5.1

core-api/src/main/java/com/jraska/github/client/analytics/AnalyticsEvent.kt, feature/push/src/main/java/com/jraska/github/client/push/PushAction.kt, feature/push/src/test/java/com/jraska/github/client/push/RemoteMessageToActionConverterTest.kt, feature/users/src/main/java/com/jraska/github/client/users/model/GitHubApiUsersRepository.kt, feature/users/src/main/java/com/jraska/github/client/users/model/UserDetail.kt
=> Use Kotlin immutable collections instead of Collections.unmodifiable*

core/build.gradle, core/src/main/java/com/jraska/github/client/AppVersion.kt, core/src/main/java/com/jraska/github/client/http/AppCommonHeadersInterceptor.kt, core/src/main/java/com/jraska/github/client/http/HttpModule.kt, core/src/main/java/com/jraska/github/client/http/NetworkSequenceNumber.kt, core/src/test/java/com/jraska/github/client/http/AppCommonHeadersInterceptorTest.kt
- Simple example how to add some basic headers
- `User-Agent`, `RequestId`, `Sequence-Number`
=> Add common headers for network requests

feature/settings/build.gradle, feature/settings/src/main/java/com/jraska/github/client/settings/IntegrityCheck.kt, feature/settings/src/main/java/com/jraska/github/client/settings/IntegrityCheckModel.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsActivity.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsViewModel.kt, feature/settings/src/main/res/layout/item_row_integrity.xml, feature/settings/src/main/res/values/strings.xml
- Playground feature to try the Integrity API
- https://developer.android.com/google/play/integrity/verdict
- Generating nonce locally as ranodm
=> Add test IntegrityCheck to settings

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-android-testing/build.gradle, core-testing/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/config-debug/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/performance/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/ui-common-api/build.gradle, feature/users/build.gradle
- This Gradle configuration is not required anymore
=> Remove unnecessary target Kotlin versions

plugins/src/main/java/com/jraska/github/client/firebase/Device.kt, plugins/src/main/java/com/jraska/github/client/firebase/TestConfiguration.kt, plugins/src/test/kotlin/com/jraska/github/client/firebase/report/FirebaseOutputParserTest.kt
- 3 devices was unnecessary + the one device is flaky
=> Remove Pixel 2 from devices on test lab

app/src/androidTest/java/com/jraska/github/client/EnableConfigRule.kt, app/src/androidTest/java/com/jraska/github/client/users/UsersActivityFlowTest.kt, app/src/androidTest/java/com/jraska/github/client/xpush/PushIntegrationTest.kt, core-testing/src/main/java/com/jraska/github/client/FakeConfig.kt, core-testing/src/main/java/com/jraska/github/client/RecordingAnalyticsProperty.kt, feature/push/src/main/java/com/jraska/github/client/push/PressBackButtonCommand.kt
Tested
- `ConfigAsPropertyCommand`
- `LaunchDeepLinkCommand`
- `PressBackButtonCommand`
- `RefreshConfigCommand`
- `SetAnalyticsPropertyCommand`
=> Add Push tests for multiple Push actions

app-partial-users/build.gradle, core/build.gradle, core/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt, core/src/main/java/com/jraska/github/client/core/push/ConfigAsPropertyCommand.kt, core/src/main/java/com/jraska/github/client/core/push/LaunchDeepLinkCommand.kt, core/src/main/java/com/jraska/github/client/core/push/RefreshConfigCommand.kt, core/src/main/java/com/jraska/github/client/core/push/SetAnalyticsPropertyCommand.kt, feature/push/src/main/java/com/jraska/github/client/push/PushModule.kt
- analytics, config and deep links to `:core`
=> Move push commands to different modules

.github/workflows/build.yml
- Test running R8
- Prevent issues discovery at the time of release
=> Add release to Ci

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/release_trigger.yml, .github/workflows/reporting.yml
- Keeping up to date
- Avoiding the deprecated node warnings
=> Use Checkout v3 action

feature/identity-api/build.gradle, feature/identity-api/src/main/AndroidManifest.xml, feature/identity-api/src/main/java/com/jraska/github/client/identity/google/GoogleSignInFactory.kt, feature/identity/build.gradle, feature/identity/src/main/java/com/jraska/github/client/identity/IdentityModule.kt, feature/identity/src/main/java/com/jraska/github/client/identity/google/GoogleSignInFragment.kt, feature/identity/src/main/java/com/jraska/github/client/identity/google/GoogleSignInRepository.kt, feature/identity/src/main/java/com/jraska/github/client/identity/google/GoogleSignInViewModel.kt, feature/identity/src/main/res/layout/identity_google_login.xml, feature/identity/src/main/res/values/strings.xml, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsActivity.kt, feature/settings/src/main/java/com/jraska/github/client/settings/SettingsViewModel.kt, feature/settings/src/main/res/layout/content_settings.xml
- to get some learnings in production
=> Add first version of Google SignIn

feature/identity/src/main/java/com/jraska/github/client/identity/google/GoogleSignInRepository.kt, feature/identity/src/main/java/com/jraska/github/client/identity/google/GoogleSignInViewModel.kt
- get more info from production
=> Add analytics event to sign in

core/src/main/java/com/jraska/github/client/http/ErrorLoggingConverterFactory.kt, core/src/main/java/com/jraska/github/client/http/HttpModule.kt, core/src/test/java/com/jraska/github/client/http/ErrorLoggingConverterFactoryTest.kt
- Hook into Retrofit converters
- For now Logging as error in `Timber`
=> Add Network Converting errors logging

core/src/main/java/com/jraska/github/client/http/ClientThrottlingInterceptor.kt, core/src/test/java/com/jraska/github/client/http/RequestRejectionRegistryTest.kt
- https://sre.google/sre-book/handling-overload/
- Related to #825
=> Expire throttling in 2 minutes

.github/workflows/build.yml
=> Remove extra Get Dependencies steps

app/build.gradle
=> Bumpt TripleT to 3.8.2

feature/in-app-update/src/main/java/com/jraska/github/client/inappupdate/UpdateChecker.kt
- Was printing obfuscated class name only
=> Remove printing class name in UpdateChecker

core-testing/src/main/java/com/jraska/github/client/TestTimeProvider.kt, core/build.gradle, core/src/main/java/com/jraska/github/client/http/HttpTrackingInterceptor.kt, core/src/main/java/com/jraska/github/client/http/NetworkResource.kt, core/src/main/java/com/jraska/github/client/http/NetworkResourceReporter.kt, core/src/test/java/com/jraska/github/client/http/HttpTrackingInterceptorTest.kt, core/src/test/java/com/jraska/github/client/http/RequestRejectionRegistryTest.kt
Basic reporting to check BigQuery capabilities
=> Report network events to analytics

core-testing/src/main/java/com/jraska/github/client/http/FakeHttpModule.kt, core-testing/src/main/java/com/jraska/github/client/http/FakeImagesInterceptor.kt, core-testing/src/main/java/com/jraska/github/client/http/HttpTest.kt, core/build.gradle, core/src/main/java/com/jraska/github/client/core/android/CoreAndroidModule.kt
- Found time to finally fake the images in UI tests
- Same instance of OkHttp client is used for now - Response cache will be shared, but whatever
- Hardcoded image into code - 315 bytes 🤷
=> Use OkHttp for images

app/build.gradle, app/src/main/java/com/jraska/github/client/GitHubClientApp.kt, build.gradle, feature/push/build.gradle
- wasn't used
- Its code is thought a good inspiration :)
=> Remove Firebase Performance

core/build.gradle, dependencies.gradle
- avoiding dependabot doing separate updates
- Related to https://github.com/jraska/github-client/issues/890
- Didn't find any up-to-date reference on Fresco - no idea if I'm unique :P
=> Align fresco versions

core/src/main/java/com/jraska/github/client/http/HttpTrackingInterceptor.kt, core/src/main/java/com/jraska/github/client/http/NetworkResource.kt, core/src/main/java/com/jraska/github/client/http/NetworkResourceReporter.kt, core/src/test/java/com/jraska/github/client/http/HttpTrackingInterceptorTest.kt
- Checking simple header `Content-Type`
=> Add content-type to network tracking

app/build.gradle
- [Plugin portal](https://plugins.gradle.org/plugin/com.jraska.module.graph.assertion/2.4.0)
- [Changelog](https://github.com/jraska/modules-graph-assert/releases)
=> Bump module-graph-assert plugin to 2.4.0

app/build.gradle
=> Bump module-graph-assert plugin to 2.4.1

app/build.gradle
- [Release notes](https://github.com/jraska/modules-graph-assert/releases/tag/2.5.0)
=> module-graph-assert 2.5.0

app-partial-users/build.gradle, app/build.gradle, core-android-api/build.gradle, core-android-testing/build.gradle, core-testing/build.gradle, core/build.gradle, feature/about/build.gradle, feature/chrome-custom-tabs/build.gradle, feature/config-debug/build.gradle, feature/identity-api/build.gradle, feature/identity/build.gradle, feature/in-app-update/build.gradle, feature/network-status/build.gradle, feature/performance/build.gradle, feature/push/build.gradle, feature/repo/build.gradle, feature/settings/build.gradle, feature/shortcuts/build.gradle, feature/ui-common-api/build.gradle, feature/users/build.gradle
=> Use compileSdk instead of compileSdkVersion

plugins/gradle/wrapper/gradle-wrapper.properties
- to keep in sync with main app
=> Gradle 8.3 to composite builds

plugins/src/main/java/com/jraska/appsize/AppSizeReport.kt, plugins/src/main/java/com/jraska/appsize/diff/AppSizeDiff.kt, plugins/src/main/java/com/jraska/appsize/diff/AppSizeDiffPrinter.kt, plugins/src/main/java/com/jraska/appsize/diff/AppSizeDiffer.kt, plugins/src/test/kotlin/com/jraska/appsize/AppSizeTest.kt, plugins/src/test/kotlin/com/jraska/appsize/RulerJsonParserTest.kt, plugins/src/test/kotlin/com/jraska/appsize/diff/AppSizeDiffPrinterTest.kt, plugins/src/test/kotlin/com/jraska/appsize/diff/AppSizeDifferTest.kt, plugins/src/test/resources/appsize/ruler_report_short_for_diff.json
- Finding diffs between the Ruler JSON reports
=> Add Ruler report diffing

plugins/src/main/java/com/jraska/appsize/AppSizeReport.kt, plugins/src/main/java/com/jraska/appsize/diff/AppSizeDiff.kt, plugins/src/main/java/com/jraska/appsize/diff/AppSizeDiffPrinter.kt, plugins/src/main/java/com/jraska/appsize/diff/AppSizeDiffer.kt, plugins/src/test/resources/appsize/ruler_report_short_for_diff.json
- Better formatting for negative values
- Recognizing artifact bumps as edit, not as add/remove
- Skipping diffs < 100 Bytes
=> Ruler report diffing improvements

feature/about/build.gradle, feature/about/src/main/java/com/jraska/github/client/about/VersionInfoModel.kt, feature/about/src/main/res/layout/about_item_version.xml, feature/about/src/main/res/values/strings.xml
- simple display of the UI with packagaManager timestamps
=> Add update info

feature/chrome-custom-tabs/build.gradle, feature/chrome-custom-tabs/src/main/java/com/jraska/github/client/chrome/ChromeCustomTabsLauncher.kt
- The intent should be correct - let's verify we don't crash unnecessarily
=> Don't crash on not found app on uri intent

dependencies.gradle
- Fixed missing native library: https://github.com/facebook/fresco/issues/2722#issuecomment-1779640180
=> Update Fresco to 3.1.3

app/build.gradle
Measured diff
```
-------------------------------------------App Size Diff--------------------------------------------
From version: 0.63.0 to version: 0.63.0
Total app size diff: 
Download: -85.8 kB, Install: -85.79 kB
-----------------------------------------------Added------------------------------------------------
----------------------------------------------Removed-----------------------------------------------
----------------------------------------------Modified----------------------------------------------
com.google.android.material:material:1.10.0 Download: -72.55 kB, Install: -72.55 kB
androidx.appcompat:appcompat:1.6.1 Download: -4.03 kB, Install: -4.03 kB
androidx.core:core:1.12.0 Download: -4.02 kB, Install: -4.02 kB
:app Download: -3.95 kB, Install: -3.95 kB …
```
=> Add shrink resources

feature/in-app-update/build.gradle
- https://developer.android.com/guide/playcore#java-kotlin-in-app-update
=> Update core in app update library

app/build.gradle
- https://github.com/jraska/modules-graph-assert/releases/tag/2.6.0
=> Module Graph Assert 2.6.0
